sites:
  - name: site-1
    folder: site-1
    apic_url: https://apic.site1.local
    username: admin
    password: pass123

  - name: site-2
    folder: site-2
    apic_url: https://apic.site2.local
    username: sentinel
    password: secret456